### ISSUE TITLE
Update GitHub Actions to use newer Python version

### ISSUE THREAD

**Issue by mirenradia** [GRChombo/Postprocessing_tools#17]
The GitHub actions in this repository use Python 3.5 which is no longer available in the virtual environments (see actions/virtual-environments#4744) leading to failing actions (e.g. [this run](https://github.com/GRChombo/Postprocessing_tools/runs/5042165240?check_suite_focus=true)). These should be updated to use newer versions.

**Comment by ThomasHelfer** [comment]
https://github.com/GRChombo/Postprocessing_tools/pull/18
